### ISSUE TITLE
Blocker - No readme.srt found in package

### ISSUE THREAD

**Issue by jkeruzec** [martsberger/django-pivot#11]
Installing V1.8.0 of django-python. Package references readme.srt but is not part of package so installation is blocked.

[root@teardown ~]# pip install django-pivot
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting django-pivot
  Using cached django-pivot-1.8.0.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vkfQ21/django-pivot/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vkfQ21/django-pivot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-vkfQ21/django-pivot/pip-egg-info
         cwd: /tmp/pip-install-vkfQ21/django-pivot/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vkfQ21/django-pivot/setup.py", line 13, in <module>
        long_description=read_file('README.rst'),
      File "/tmp/pip-install-vkfQ21/django-pivot/setup.py", line 5, in read_file
        with open(name) as fd:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by martsberger** [comment]
This should be fixed in version 1.8.1, please let me know if this is still an issue.
