### ISSUE TITLE
force_text in django_pivot.utils.py is depricated for django  >=3.0

### ISSUE THREAD

**Issue by osvill** [martsberger/django-pivot#12]
First I want to thank you for this great package! I'm using it intensively!

As described in the title I'm encountering warnings from the imported method `force_text` from `django.utils.encoding` in `django_pivot.utils.py` in line 20. 

It recommends to use the new method `force_str` introduced in django v3 in `django.utils.encoding`, see [here](https://github.com/django/django/commit/d55e88292723764a16f0689c73bc7e739dfa6047#diff-d3fe562051dcbab80f60f067fa6a5838) .

Maybe a version check of django in `django_pivot.utils.py` in line 20 could help.

**Comment by martsberger** [comment]
Thanks for brining this up. Do you want to submit a PR for this?

Also need to add Django 3.0 to the travis.yml
