### ISSUE TITLE
ModuleNotFoundError: No module named 'django_pivot'

### ISSUE THREAD

**Issue by christophschoeni** [martsberger/django-pivot#19]
After install the module i set the app in settings, but i become an error:
ModuleNotFoundError: No module named 'django_pivot'

**Comment by htukiain** [comment]
What is your import statement?
My import is
`from django_pivot.pivot import pivot`

**Comment by OlgaKuzminova** [comment]
After install the module i set the app in settings, but i become an error too:
ModuleNotFoundError: No module named 'django_pivot'
My import is
from django_pivot.pivot import pivot

**Comment by OlgaKuzminova** [comment]
Found the answer:
no need to put django_pivot in installed apps in your settings file
